"use client"
import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'

type Mode = 'sign-in' | 'sign-up'
export default function AuthPage() {
  const router = useRouter(); const [mode, setMode] = useState<Mode>('sign-up'), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const form = new FormData(event.currentTarget); const response = await fetch(`/api/auth/${mode}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); const data = await response.json(); if (!data.error && mode === 'sign-in') { router.push('/?spotify=connect'); return }; setMessage(data.error || data.message || 'Something went wrong.'); setBusy(false) }
  return <main className="min-h-screen bg-[#15332f] p-6 text-[#f1eadc]"><div className="mx-auto mt-[12vh] max-w-md border border-[#f1eadc]/35 bg-[#1c3b35] p-8 shadow-2xl"><a href="/" className="font-bold tracking-[.18em]">REEL<span className="font-serif text-2xl font-normal tracking-tighter">studio</span></a><p className="mt-10 font-mono text-[10px] tracking-[.14em] text-[#cad6c6]">YOUR LISTENING ROOM</p><h1 className="mt-2 font-serif text-4xl">{mode === 'sign-up' ? 'Make a place for your tapes.' : 'Welcome back.'}</h1><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-xs">Email<input required name="email" type="email" autoComplete="email" className="mt-2 w-full border border-[#b8c6b4] bg-[#f1eadc] px-3 py-3 text-[#203431] outline-none" placeholder="you@example.com"/></label><label className="block text-xs">Password<input required minLength={8} name="password" type="password" autoComplete={mode === 'sign-up' ? 'new-password' : 'current-password'} className="mt-2 w-full border border-[#b8c6b4] bg-[#f1eadc] px-3 py-3 text-[#203431] outline-none" placeholder="At least 8 characters"/></label><button disabled={busy} className="w-full bg-[#e85d3f] py-3 font-mono text-xs font-bold tracking-widest disabled:opacity-60">{busy ? 'PLEASE WAIT…' : mode === 'sign-up' ? 'CREATE ACCOUNT' : 'SIGN IN'}</button></form>{message && <p className="mt-4 border-l-2 border-[#f5c052] pl-3 text-sm text-[#f4e9d5]" role="status">{message}</p>}<div className="mt-7 flex items-center justify-between border-t border-[#f1eadc]/25 pt-5 text-xs"><button onClick={() => { setMode(mode === 'sign-up' ? 'sign-in' : 'sign-up'); setMessage('') }} className="underline">{mode === 'sign-up' ? 'Already have an account?' : 'Need an account?'}</button><a className="text-[#f5c052]" href="/api/spotify/authorize">Connect Spotify →</a></div></div></main>
}